import { TextTool } from '../../core/models/text-tool.model';

export const TEXT_TOOLS: TextTool[] = [
  {
    id: 'upper',
    name: 'UPPERCASE',
    description: 'Convert all text to uppercase',
    category: 'case',
    icon: 'case-upper',
  },
  {
    id: 'lower',
    name: 'lowercase',
    description: 'Convert all text to lowercase',
    category: 'case',
    icon: 'case-lower',
  },
  {
    id: 'title',
    name: 'Title Case',
    description: 'Capitalize each word',
    category: 'case',
    icon: 'type',
  },
  {
    id: 'sentence',
    name: 'Sentence case',
    description: 'Normalize sentence capitalization',
    category: 'case',
    icon: 'pilcrow',
  },
  {
    id: 'camel',
    name: 'camelCase',
    description: 'Convert words to camelCase',
    category: 'case',
    icon: 'braces',
  },
  {
    id: 'pascal',
    name: 'PascalCase',
    description: 'Convert words to PascalCase',
    category: 'case',
    icon: 'braces',
  },
  {
    id: 'snake',
    name: 'snake_case',
    description: 'Convert words to snake_case',
    category: 'case',
    icon: 'code-2',
  },
  {
    id: 'kebab',
    name: 'kebab-case',
    description: 'Convert words to kebab-case',
    category: 'case',
    icon: 'code-2',
  },
  {
    id: 'constant',
    name: 'CONSTANT_CASE',
    description: 'Convert words to CONSTANT_CASE',
    category: 'case',
    icon: 'code-2',
  },
  {
    id: 'trim',
    name: 'Trim text',
    description: 'Remove surrounding whitespace',
    category: 'cleanup',
    icon: 'scissors',
  },
  {
    id: 'spaces',
    name: 'Clean spaces',
    description: 'Normalize repeated spaces',
    category: 'cleanup',
    icon: 'wand-sparkles',
  },
  {
    id: 'empty',
    name: 'Remove empty lines',
    description: 'Delete blank lines',
    category: 'cleanup',
    icon: 'list-minus',
  },
  {
    id: 'duplicates',
    name: 'Remove duplicates',
    description: 'Remove duplicate lines',
    category: 'lines',
    icon: 'copy-minus',
  },
  {
    id: 'sortAsc',
    name: 'Sort A → Z',
    description: 'Sort lines ascending',
    category: 'lines',
    icon: 'arrow-down-a-z',
  },
  {
    id: 'sortDesc',
    name: 'Sort Z → A',
    description: 'Sort lines descending',
    category: 'lines',
    icon: 'arrow-up-z-a',
  },
  {
    id: 'reverseLines',
    name: 'Reverse lines',
    description: 'Reverse line order',
    category: 'lines',
    icon: 'arrow-up-down',
  },
  {
    id: 'reverseText',
    name: 'Reverse text',
    description: 'Reverse every character',
    category: 'lines',
    icon: 'refresh-cw',
  },
  {
    id: 'number',
    name: 'Number lines',
    description: 'Add numbers to each line',
    category: 'lines',
    icon: 'list-ordered',
  },
  {
    id: 'urlEncode',
    name: 'URL Encode',
    description: 'Encode text for URLs',
    category: 'encode',
    icon: 'link',
  },
  {
    id: 'urlDecode',
    name: 'URL Decode',
    description: 'Decode URL text',
    category: 'encode',
    icon: 'unlink',
  },
  {
    id: 'base64Encode',
    name: 'Base64 Encode',
    description: 'Encode text as Base64',
    category: 'encode',
    icon: 'binary',
  },
  {
    id: 'base64Decode',
    name: 'Base64 Decode',
    description: 'Decode Base64 text',
    category: 'encode',
    icon: 'binary',
  },
  {
    id: 'htmlEncode',
    name: 'HTML Encode',
    description: 'Escape HTML characters',
    category: 'encode',
    icon: 'code-xml',
  },
  {
    id: 'htmlDecode',
    name: 'HTML Decode',
    description: 'Decode HTML entities',
    category: 'encode',
    icon: 'code-xml',
  },
  {
    id: 'jsonPretty',
    name: 'JSON Pretty',
    description: 'Format JSON with indentation',
    category: 'developer',
    icon: 'braces',
  },
  {
    id: 'jsonMinify',
    name: 'JSON Minify',
    description: 'Compress JSON',
    category: 'developer',
    icon: 'minimize-2',
  },
];
