import { TextTool } from '../../core/models/text-tool.model';

export const TEXT_TOOLS: TextTool[] = [
  {
    id: 'upper',
    name: 'UPPERCASE',
    description: 'Convert all text to uppercase',
    category: 'format',
    icon: 'case-upper',
  },
  {
    id: 'lower',
    name: 'lowercase',
    description: 'Convert all text to lowercase',
    category: 'format',
    icon: 'case-lower',
  },
  {
    id: 'title',
    name: 'Title Case',
    description: 'Capitalize each word',
    category: 'format',
    icon: 'type',
  },
  {
    id: 'sentence',
    name: 'Sentence case',
    description: 'Normalize sentence capitalization',
    category: 'format',
    icon: 'pilcrow',
  },
  {
    id: 'camel',
    name: 'camelCase',
    description: 'Developer camel case',
    category: 'format',
    icon: 'braces',
  },
  {
    id: 'pascal',
    name: 'PascalCase',
    description: 'Developer Pascal case',
    category: 'format',
    icon: 'braces',
  },
  {
    id: 'snake',
    name: 'snake_case',
    description: 'Developer snake case',
    category: 'format',
    icon: 'code-2',
  },
  {
    id: 'kebab',
    name: 'kebab-case',
    description: 'Developer kebab case',
    category: 'format',
    icon: 'minus',
  },
  {
    id: 'constant',
    name: 'CONSTANT_CASE',
    description: 'Constant naming style',
    category: 'format',
    icon: 'case-upper',
  },
  {
    id: 'dot',
    name: 'dot.case',
    description: 'Dot-separated words',
    category: 'format',
    icon: 'ellipsis',
  },
  {
    id: 'path',
    name: 'path/case',
    description: 'Slash-separated words',
    category: 'format',
    icon: 'folder-tree',
  },
  {
    id: 'slug',
    name: 'Slug Generator',
    description: 'Create URL-friendly slug',
    category: 'format',
    icon: 'link',
  },
  {
    id: 'trim',
    name: 'Trim Text',
    description: 'Remove surrounding whitespace',
    category: 'cleanup',
    icon: 'scissors',
  },
  {
    id: 'spaces',
    name: 'Clean Spaces',
    description: 'Normalize repeated whitespace',
    category: 'cleanup',
    icon: 'sparkles',
  },
  {
    id: 'empty',
    name: 'Remove Empty Lines',
    description: 'Delete blank lines',
    category: 'cleanup',
    icon: 'list-minus',
  },
  {
    id: 'duplicates',
    name: 'Remove Duplicate Lines',
    description: 'Keep unique lines',
    category: 'cleanup',
    icon: 'copy-minus',
  },
  {
    id: 'uniqueWords',
    name: 'Unique Words',
    description: 'Extract unique words',
    category: 'cleanup',
    icon: 'list-filter',
  },
  {
    id: 'diacritics',
    name: 'Remove Diacritics',
    description: 'Convert accented letters',
    category: 'cleanup',
    icon: 'eraser',
  },
  {
    id: 'unicode',
    name: 'Normalize Unicode',
    description: 'Normalize Unicode to NFC',
    category: 'cleanup',
    icon: 'languages',
  },
  {
    id: 'removeHtml',
    name: 'Strip HTML',
    description: 'Extract plain text from HTML',
    category: 'cleanup',
    icon: 'code-xml',
  },
  {
    id: 'sortAsc',
    name: 'Sort Lines A–Z',
    description: 'Sort lines ascending',
    category: 'lines',
    icon: 'arrow-down-a-z',
  },
  {
    id: 'sortDesc',
    name: 'Sort Lines Z–A',
    description: 'Sort lines descending',
    category: 'lines',
    icon: 'arrow-up-z-a',
  },
  {
    id: 'reverseLines',
    name: 'Reverse Lines',
    description: 'Reverse line order',
    category: 'lines',
    icon: 'arrow-up-down',
  },
  {
    id: 'reverseText',
    name: 'Reverse Text',
    description: 'Reverse all characters',
    category: 'lines',
    icon: 'refresh-cw',
  },
  {
    id: 'shuffleLines',
    name: 'Shuffle Lines',
    description: 'Randomize line order',
    category: 'lines',
    icon: 'shuffle',
  },
  {
    id: 'number',
    name: 'Number Lines',
    description: 'Add line numbers',
    category: 'lines',
    icon: 'list-ordered',
  },
  {
    id: 'removeNumbers',
    name: 'Remove Line Numbers',
    description: 'Strip leading numbering',
    category: 'lines',
    icon: 'list-x',
  },
  {
    id: 'bullets',
    name: 'Bullet List',
    description: 'Convert lines to bullets',
    category: 'lines',
    icon: 'list',
  },
  {
    id: 'joinLines',
    name: 'Join Lines',
    description: 'Join lines into paragraph',
    category: 'lines',
    icon: 'merge',
  },
  {
    id: 'tabsSpaces',
    name: 'Tabs → Spaces',
    description: 'Replace tabs with spaces',
    category: 'lines',
    icon: 'arrow-right',
  },
  {
    id: 'spacesTabs',
    name: 'Spaces → Tabs',
    description: 'Convert leading spaces',
    category: 'lines',
    icon: 'arrow-left',
  },
  {
    id: 'urlEncode',
    name: 'URL Encode',
    description: 'Encode URL-safe text',
    category: 'convert',
    icon: 'link',
  },
  {
    id: 'urlDecode',
    name: 'URL Decode',
    description: 'Decode URL text',
    category: 'convert',
    icon: 'unlink',
  },
  {
    id: 'base64Encode',
    name: 'Base64 Encode',
    description: 'Encode UTF-8 text',
    category: 'convert',
    icon: 'binary',
  },
  {
    id: 'base64Decode',
    name: 'Base64 Decode',
    description: 'Decode Base64 UTF-8',
    category: 'convert',
    icon: 'binary',
  },
  {
    id: 'htmlEncode',
    name: 'HTML Entities Encode',
    description: 'Escape HTML characters',
    category: 'convert',
    icon: 'code-xml',
  },
  {
    id: 'htmlDecode',
    name: 'HTML Entities Decode',
    description: 'Decode HTML entities',
    category: 'convert',
    icon: 'code-xml',
  },
  {
    id: 'rot13',
    name: 'ROT13',
    description: 'Apply ROT13 substitution',
    category: 'convert',
    icon: 'repeat-2',
  },
  {
    id: 'textBinary',
    name: 'Text → Binary',
    description: 'Convert UTF-8 to binary',
    category: 'convert',
    icon: 'binary',
  },
  {
    id: 'binaryText',
    name: 'Binary → Text',
    description: 'Convert binary bytes to text',
    category: 'convert',
    icon: 'binary',
  },
  {
    id: 'textHex',
    name: 'Text → Hex',
    description: 'Convert UTF-8 to hexadecimal',
    category: 'convert',
    icon: 'hash',
  },
  {
    id: 'hexText',
    name: 'Hex → Text',
    description: 'Convert hexadecimal to text',
    category: 'convert',
    icon: 'hash',
  },
  {
    id: 'jsonPretty',
    name: 'JSON Formatter',
    description: 'Pretty-print JSON',
    category: 'code',
    icon: 'braces',
  },
  {
    id: 'jsonMinify',
    name: 'JSON Minifier',
    description: 'Compress JSON',
    category: 'code',
    icon: 'minimize-2',
  },
  {
    id: 'jsonValidate',
    name: 'JSON Validator',
    description: 'Validate JSON syntax',
    category: 'code',
    icon: 'badge-check',
  },
  {
    id: 'csvJson',
    name: 'CSV → JSON',
    description: 'Convert CSV records to JSON',
    category: 'code',
    icon: 'table',
  },
  {
    id: 'jsonCsv',
    name: 'JSON → CSV',
    description: 'Convert JSON array to CSV',
    category: 'code',
    icon: 'table',
  },
  {
    id: 'escapeJs',
    name: 'Escape String',
    description: 'Escape JavaScript string content',
    category: 'developer',
    icon: 'code',
  },
  {
    id: 'unescapeJs',
    name: 'Unescape String',
    description: 'Unescape JavaScript string content',
    category: 'developer',
    icon: 'code',
  },
  {
    id: 'emails',
    name: 'Extract Emails',
    description: 'Find unique email addresses',
    category: 'analyze',
    icon: 'mail',
  },
  {
    id: 'urls',
    name: 'Extract URLs',
    description: 'Find unique web URLs',
    category: 'analyze',
    icon: 'link',
  },
  {
    id: 'numbersOnly',
    name: 'Extract Numbers',
    description: 'Find numbers in text',
    category: 'analyze',
    icon: 'binary',
  },
  {
    id: 'hashtags',
    name: 'Extract Hashtags',
    description: 'Find unique hashtags',
    category: 'analyze',
    icon: 'hash',
  },
  {
    id: 'frequency',
    name: 'Word Frequency',
    description: 'Count occurrences of each word',
    category: 'analyze',
    icon: 'bar-chart-3',
  },
  {
    id: 'lineLength',
    name: 'Line Length Report',
    description: 'Show character count per line',
    category: 'analyze',
    icon: 'ruler',
  },
  {
    id: 'password',
    name: 'Password Generator',
    description: 'Generate secure 20-character password',
    category: 'generate',
    icon: 'key-round',
  },
  {
    id: 'passphrase',
    name: 'Passphrase Generator',
    description: 'Generate memorable passphrase',
    category: 'generate',
    icon: 'key',
  },
  {
    id: 'uuid',
    name: 'UUID Generator',
    description: 'Generate UUID v4',
    category: 'generate',
    icon: 'fingerprint',
  },
  {
    id: 'random',
    name: 'Random String',
    description: 'Generate random 32-character string',
    category: 'generate',
    icon: 'dices',
  },
  {
    id: 'lorem',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder paragraph',
    category: 'generate',
    icon: 'text',
  },
  {
    id: 'timestamp',
    name: 'Timestamp Generator',
    description: 'Generate Unix and ISO timestamps',
    category: 'generate',
    icon: 'clock',
  },
  {
    id: 'sha256',
    name: 'SHA-256',
    description: 'Create SHA-256 text fingerprint',
    category: 'security',
    icon: 'shield-check',
  },
];

export const TOOL_CATEGORIES = [
  { id: 'all', name: 'All Tools', icon: 'layout-grid' },
  { id: 'format', name: 'Formatting', icon: 'type' },
  { id: 'cleanup', name: 'Cleanup', icon: 'sparkles' },
  { id: 'lines', name: 'Lines & Lists', icon: 'list' },
  { id: 'convert', name: 'Conversion', icon: 'arrow-left-right' },
  { id: 'code', name: 'Code & Data', icon: 'code-2' },
  { id: 'generate', name: 'Generators', icon: 'wand-sparkles' },
  { id: 'analyze', name: 'Analysis', icon: 'chart-no-axes-column' },
  { id: 'developer', name: 'Developer', icon: 'terminal' },
  { id: 'security', name: 'Security', icon: 'shield' },
];
