import { TextTool, ToolCategoryItem } from '../../core/models/text-tool.model';

export const TOOL_CATEGORIES: ToolCategoryItem[] = [
  { id: 'all', name: 'All Tools', icon: 'layout-grid' },
  { id: 'format', name: 'Formatting', icon: 'type' },
  { id: 'cleanup', name: 'Cleanup', icon: 'sparkles' },
  { id: 'lines', name: 'Lines & Lists', icon: 'list' },
  { id: 'convert', name: 'Conversion', icon: 'arrow-left-right' },
  { id: 'code', name: 'Code & Data', icon: 'code-2' },
  { id: 'generate', name: 'Generators', icon: 'wand-sparkles' },
  { id: 'analyze', name: 'Analysis', icon: 'chart-no-axes-column' },
  { id: 'developer', name: 'Developer', icon: 'terminal' },
  { id: 'security', name: 'Security', icon: 'shield-check' },
];

export const TEXT_TOOLS: TextTool[] = [
  {
    id: 'upper',
    name: 'Uppercase',
    shortName: 'AB',
    description: 'Convert selection or document to uppercase',
    category: 'format',
    icon: 'case-upper',
    behavior: 'transform',
  },
  {
    id: 'lower',
    name: 'Lowercase',
    shortName: 'ab',
    description: 'Convert selection or document to lowercase',
    category: 'format',
    icon: 'case-lower',
    behavior: 'transform',
  },
  {
    id: 'title',
    name: 'Title Case',
    shortName: 'Tt',
    description: 'Capitalize each word',
    category: 'format',
    icon: 'type',
    behavior: 'transform',
  },
  {
    id: 'sentence',
    name: 'Sentence Case',
    shortName: 'St',
    description: 'Normalize sentence capitalization',
    category: 'format',
    icon: 'pilcrow',
    behavior: 'transform',
  },
  {
    id: 'camel',
    name: 'camelCase',
    shortName: 'cC',
    description: 'Convert words to camelCase',
    category: 'format',
    icon: 'braces',
    behavior: 'transform',
  },
  {
    id: 'pascal',
    name: 'PascalCase',
    shortName: 'PC',
    description: 'Convert words to PascalCase',
    category: 'format',
    icon: 'braces',
    behavior: 'transform',
  },
  {
    id: 'snake',
    name: 'snake_case',
    shortName: 's_c',
    description: 'Convert words to snake_case',
    category: 'format',
    icon: 'code-2',
    behavior: 'transform',
  },
  {
    id: 'kebab',
    name: 'kebab-case',
    shortName: 'k-c',
    description: 'Convert words to kebab-case',
    category: 'format',
    icon: 'minus',
    behavior: 'transform',
  },
  {
    id: 'constant',
    name: 'CONSTANT_CASE',
    shortName: 'C_C',
    description: 'Convert words to CONSTANT_CASE',
    category: 'format',
    icon: 'case-upper',
    behavior: 'transform',
  },
  {
    id: 'dot',
    name: 'dot.case',
    shortName: 'a.b',
    description: 'Convert words to dot.case',
    category: 'format',
    icon: 'ellipsis',
    behavior: 'transform',
  },
  {
    id: 'path',
    name: 'path/case',
    shortName: 'a/b',
    description: 'Convert words to path/case',
    category: 'format',
    icon: 'folder-tree',
    behavior: 'transform',
  },
  {
    id: 'slug',
    name: 'Slug Generator',
    shortName: 'slug',
    description: 'Create URL-friendly slug',
    category: 'format',
    icon: 'link',
    behavior: 'transform',
  },

  {
    id: 'trim',
    name: 'Trim Text',
    shortName: 'Trim',
    description: 'Remove surrounding whitespace',
    category: 'cleanup',
    icon: 'scissors',
    behavior: 'transform',
  },
  {
    id: 'spaces',
    name: 'Clean Spaces',
    shortName: 'Space',
    description: 'Normalize repeated spaces',
    category: 'cleanup',
    icon: 'sparkles',
    behavior: 'transform',
  },
  {
    id: 'empty',
    name: 'Remove Empty Lines',
    shortName: 'Empty',
    description: 'Delete blank lines',
    category: 'cleanup',
    icon: 'list-minus',
    behavior: 'transform',
  },
  {
    id: 'duplicates',
    name: 'Remove Duplicate Lines',
    shortName: 'Dup',
    description: 'Keep unique lines only',
    category: 'cleanup',
    icon: 'copy-minus',
    behavior: 'transform',
  },
  {
    id: 'uniqueWords',
    name: 'Unique Words',
    shortName: 'Unique',
    description: 'Extract unique words',
    category: 'cleanup',
    icon: 'list-filter',
    behavior: 'transform',
  },
  {
    id: 'diacritics',
    name: 'Remove Diacritics',
    shortName: 'Accent',
    description: 'Remove accents from letters',
    category: 'cleanup',
    icon: 'eraser',
    behavior: 'transform',
  },
  {
    id: 'unicode',
    name: 'Normalize Unicode',
    shortName: 'UTF',
    description: 'Normalize Unicode using NFC',
    category: 'cleanup',
    icon: 'languages',
    behavior: 'transform',
  },
  {
    id: 'removeHtml',
    name: 'Strip HTML',
    shortName: 'HTML-',
    description: 'Extract plain text from HTML',
    category: 'cleanup',
    icon: 'code-xml',
    behavior: 'transform',
  },

  {
    id: 'sortAsc',
    name: 'Sort A–Z',
    shortName: 'A-Z',
    description: 'Sort lines ascending',
    category: 'lines',
    icon: 'arrow-down-a-z',
    behavior: 'transform',
  },
  {
    id: 'sortDesc',
    name: 'Sort Z–A',
    shortName: 'Z-A',
    description: 'Sort lines descending',
    category: 'lines',
    icon: 'arrow-up-z-a',
    behavior: 'transform',
  },
  {
    id: 'reverseLines',
    name: 'Reverse Lines',
    shortName: 'Rev',
    description: 'Reverse line order',
    category: 'lines',
    icon: 'arrow-up-down',
    behavior: 'transform',
  },
  {
    id: 'reverseText',
    name: 'Reverse Text',
    shortName: 'TxR',
    description: 'Reverse every character',
    category: 'lines',
    icon: 'refresh-cw',
    behavior: 'transform',
  },
  {
    id: 'shuffleLines',
    name: 'Shuffle Lines',
    shortName: 'Mix',
    description: 'Randomize line order',
    category: 'lines',
    icon: 'shuffle',
    behavior: 'transform',
  },
  {
    id: 'number',
    name: 'Number Lines',
    shortName: '1.',
    description: 'Add sequential numbers',
    category: 'lines',
    icon: 'list-ordered',
    behavior: 'transform',
  },
  {
    id: 'removeNumbers',
    name: 'Remove Line Numbers',
    shortName: '1-',
    description: 'Remove leading numbering',
    category: 'lines',
    icon: 'list-x',
    behavior: 'transform',
  },
  {
    id: 'bullets',
    name: 'Bullet List',
    shortName: '•',
    description: 'Convert lines to bullets',
    category: 'lines',
    icon: 'list',
    behavior: 'transform',
  },
  {
    id: 'joinLines',
    name: 'Join Lines',
    shortName: 'Join',
    description: 'Join lines into one paragraph',
    category: 'lines',
    icon: 'merge',
    behavior: 'transform',
  },
  {
    id: 'tabsSpaces',
    name: 'Tabs to Spaces',
    shortName: 'T→S',
    description: 'Replace tabs with four spaces',
    category: 'lines',
    icon: 'arrow-right',
    behavior: 'transform',
  },
  {
    id: 'spacesTabs',
    name: 'Spaces to Tabs',
    shortName: 'S→T',
    description: 'Convert leading spaces to tabs',
    category: 'lines',
    icon: 'arrow-left',
    behavior: 'transform',
  },

  {
    id: 'urlEncode',
    name: 'URL Encode',
    shortName: 'URL+',
    description: 'Encode text for URLs',
    category: 'convert',
    icon: 'link',
    behavior: 'transform',
  },
  {
    id: 'urlDecode',
    name: 'URL Decode',
    shortName: 'URL-',
    description: 'Decode URL text',
    category: 'convert',
    icon: 'unlink',
    behavior: 'transform',
  },
  {
    id: 'base64Encode',
    name: 'Base64 Encode',
    shortName: 'B64+',
    description: 'Encode UTF-8 text as Base64',
    category: 'convert',
    icon: 'binary',
    behavior: 'transform',
  },
  {
    id: 'base64Decode',
    name: 'Base64 Decode',
    shortName: 'B64-',
    description: 'Decode Base64 to UTF-8 text',
    category: 'convert',
    icon: 'binary',
    behavior: 'transform',
  },
  {
    id: 'htmlEncode',
    name: 'HTML Encode',
    shortName: '&+',
    description: 'Encode HTML entities',
    category: 'convert',
    icon: 'code-xml',
    behavior: 'transform',
  },
  {
    id: 'htmlDecode',
    name: 'HTML Decode',
    shortName: '&-',
    description: 'Decode HTML entities',
    category: 'convert',
    icon: 'code-xml',
    behavior: 'transform',
  },
  {
    id: 'rot13',
    name: 'ROT13',
    shortName: 'R13',
    description: 'Apply ROT13 substitution',
    category: 'convert',
    icon: 'repeat-2',
    behavior: 'transform',
  },
  {
    id: 'textBinary',
    name: 'Text to Binary',
    shortName: '→01',
    description: 'Convert UTF-8 text to binary',
    category: 'convert',
    icon: 'binary',
    behavior: 'transform',
  },
  {
    id: 'binaryText',
    name: 'Binary to Text',
    shortName: '01→',
    description: 'Convert binary bytes to text',
    category: 'convert',
    icon: 'binary',
    behavior: 'transform',
  },
  {
    id: 'textHex',
    name: 'Text to Hex',
    shortName: '→HEX',
    description: 'Convert UTF-8 text to hexadecimal',
    category: 'convert',
    icon: 'hash',
    behavior: 'transform',
  },
  {
    id: 'hexText',
    name: 'Hex to Text',
    shortName: 'HEX→',
    description: 'Convert hexadecimal to text',
    category: 'convert',
    icon: 'hash',
    behavior: 'transform',
  },

  {
    id: 'jsonPretty',
    name: 'JSON Formatter',
    shortName: '{ }',
    description: 'Pretty-print JSON',
    category: 'code',
    icon: 'braces',
    behavior: 'transform',
  },
  {
    id: 'jsonMinify',
    name: 'JSON Minifier',
    shortName: '{-}',
    description: 'Minify JSON',
    category: 'code',
    icon: 'minimize-2',
    behavior: 'transform',
  },
  {
    id: 'jsonValidate',
    name: 'JSON Validator',
    shortName: '✓{}',
    description: 'Validate JSON syntax',
    category: 'code',
    icon: 'badge-check',
    behavior: 'result',
  },
  {
    id: 'csvJson',
    name: 'CSV to JSON',
    shortName: 'CSV→{}',
    description: 'Convert CSV records to JSON',
    category: 'code',
    icon: 'table',
    behavior: 'transform',
  },
  {
    id: 'jsonCsv',
    name: 'JSON to CSV',
    shortName: '{}→CSV',
    description: 'Convert JSON array to CSV',
    category: 'code',
    icon: 'table',
    behavior: 'transform',
  },

  {
    id: 'password',
    name: 'Password Generator',
    shortName: 'Pass',
    description: 'Generate a secure password',
    category: 'generate',
    icon: 'key-round',
    behavior: 'result',
  },
  {
    id: 'passphrase',
    name: 'Passphrase Generator',
    shortName: 'Words',
    description: 'Generate a memorable passphrase',
    category: 'generate',
    icon: 'key',
    behavior: 'result',
  },
  {
    id: 'uuid',
    name: 'UUID Generator',
    shortName: 'UUID',
    description: 'Generate UUID v4',
    category: 'generate',
    icon: 'fingerprint',
    behavior: 'result',
  },
  {
    id: 'random',
    name: 'Random String',
    shortName: 'Rand',
    description: 'Generate random text',
    category: 'generate',
    icon: 'dices',
    behavior: 'result',
  },
  {
    id: 'lorem',
    name: 'Lorem Ipsum',
    shortName: 'Lorem',
    description: 'Generate placeholder text',
    category: 'generate',
    icon: 'text',
    behavior: 'result',
  },
  {
    id: 'timestamp',
    name: 'Timestamp Generator',
    shortName: 'Time',
    description: 'Generate Unix and ISO timestamps',
    category: 'generate',
    icon: 'clock',
    behavior: 'result',
  },

  {
    id: 'emails',
    name: 'Extract Emails',
    shortName: '@',
    description: 'Extract unique email addresses',
    category: 'analyze',
    icon: 'mail',
    behavior: 'result',
  },
  {
    id: 'urls',
    name: 'Extract URLs',
    shortName: 'URL',
    description: 'Extract unique URLs',
    category: 'analyze',
    icon: 'link',
    behavior: 'result',
  },
  {
    id: 'numbersOnly',
    name: 'Extract Numbers',
    shortName: '123',
    description: 'Extract numbers from text',
    category: 'analyze',
    icon: 'binary',
    behavior: 'result',
  },
  {
    id: 'hashtags',
    name: 'Extract Hashtags',
    shortName: '#',
    description: 'Extract unique hashtags',
    category: 'analyze',
    icon: 'hash',
    behavior: 'result',
  },
  {
    id: 'frequency',
    name: 'Word Frequency',
    shortName: 'Freq',
    description: 'Count word frequency',
    category: 'analyze',
    icon: 'chart-no-axes-column',
    behavior: 'result',
  },
  {
    id: 'lineLength',
    name: 'Line Length Report',
    shortName: 'Len',
    description: 'Measure every line',
    category: 'analyze',
    icon: 'ruler',
    behavior: 'result',
  },

  {
    id: 'escapeJs',
    name: 'Escape String',
    shortName: 'Esc',
    description: 'Escape JavaScript string content',
    category: 'developer',
    icon: 'code',
    behavior: 'transform',
  },
  {
    id: 'unescapeJs',
    name: 'Unescape String',
    shortName: 'Unesc',
    description: 'Unescape JavaScript string content',
    category: 'developer',
    icon: 'code',
    behavior: 'transform',
  },

  {
    id: 'sha256',
    name: 'SHA-256',
    shortName: 'SHA',
    description: 'Create SHA-256 fingerprint',
    category: 'security',
    icon: 'shield-check',
    behavior: 'result',
  },
];
